---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  "/signup":
    post:
      summary: registers a new user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user registered
        '422':
          description: invalid user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                    password:
                      type: string
                      minLength: 6
                    name:
                      type: string
                  required:
                  - email
                  - password
                  - name
        required: true
  "/login":
    post:
      summary: logs a user in
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user logged in
        '422':
          description: invalid user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                    password:
                      type: string
                      minLength: 6
                  required:
                  - email
                  - password
        required: true
  "/logout":
    delete:
      summary: logs a user out
      tags:
      - Users
      security:
      - bearerAuth: {}
      responses:
        '200':
          description: user logged out
        '401':
          description: active session not found
  "/snippets":
    get:
      summary: displays the current user's snippets
      tags:
      - Snippets
      security:
      - bearerAuth: {}
      responses:
        '200':
          description: user logged out
        '401':
          description: active session not found
    post:
      summary: creates a new snippet for the current user
      tags:
      - Snippets
      security:
      - bearerAuth: {}
      parameters: []
      responses:
        '201':
          description: snippet created
        '422':
          description: invalid snippet
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                snippet:
                  type: object
                  properties:
                    content:
                      type: string
                  required:
                  - content
        required: true
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
